BEGIN;

ALTER TABLE "shipments"
ADD COLUMN IF NOT EXISTS "client_iva" NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS "client_total" NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS "carrier_iva" NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS "carrier_total" NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS "vorian_iva" NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS "vorian_total" NUMERIC DEFAULT 0;

COMMIT;
